version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - ./certs:/root/.postgresql
    env_file:
      - .env